### ISSUE TITLE
Investigate redundant location/comunication system

### ISSUE THREAD

**Issue by vascobnunes** [vascobnunes/CSWspacepeek#21]

**Comment by jlnfreitas** [comment]
Could use something similar to what Balua is using in their latest launch:
[Map tracking through spot findme of Balua Launch from 25/04/2016](http://share.findmespot.com/shared/faces/viewspots.jsp?glId=0scHf6UmOhIOAIsIPUtx9GcSECJy90SMV)

According to their [site](http://www.amrad.pt/balao-balua-amradamsat-ct-lars-atualizacaoii/), they actually use 3 different types of communication reporting systems:

_"1- Tracker com emissor APRS e GPS desbloqueado a funcionar em 144,8 MHz- Callsign  CS5PBAL  e CS5PBA-11 em APRS,
2- Spot the comunicações por satélite com recetor de GPS e indicação de posição de 5 em 5 minutos – emissor para satélite em 14 GHz e receção em internet;
3- Beacon para localização do payload no terreno em 434,485 MHz  (transmite bip -bip)"_

**1. APRS ("Automatic Packet Reporting System")**
With a GPS + APRS one can report the position using the 144.8MHz frequency. 
It requires a radio amateur license. Our colleague [António Alves](https://wise.critical.pt/wiseweb/users/UserDetails.action?login=aalves&companyId=1) should have one. 
We have 3 options: use a COTS tracker, build our own tracker or assemble an Arduino or Pi based Kit. The 3 options are reviewed below:

a) We can either use a COTS equipment such as [Tracksoar](https://www.tracksoar.com/) ( incudes temperature, pressure, and humidity sensors, GPS receiver and antenna, costs 165USD and weights 45grams). 

b) We can [build one](http://makezine.com/projects/hab-aprs-tracker/) (more difficult)

c) Or we can assemble an Arduino based or as Raspberry Pi based kit such as the [Habduino](http://www.habduino.org/) (sold as a kit by [uptronics](https://store.uputronics.com/index.php?route=product/product&path=62&product_id=57) at a cost of 145€) or the [Pi in the Sky](http://www.pi-in-the-sky.com/) sold as a kit by [Uptronics as well](https://store.uputronics.com/index.php?route=product/product&path=62&product_id=52) at a cost of 216.15€)
The [Pi in the Ski manual](http://www.pi-in-the-sky.com/data/uploads/pits-manual.pdf) provides detailed information on how to assemble the board, connect it to an existing Raspberry Pi, setup and test the reception.
The reception of the signal can be made using an RTL SDR dongle [similar to the one I have to track ADS-B signals](http://www.nooelec.com/store/sdr/sdr-receivers/nesdr-mini-rtl2832-r820t.html), but with a decent TBD antenna.

**2. Spot Satcom**
The spot satcom tracker requires a SPOT equipment with a satcom data plan (weight < 100g, cost around 150€ - equipment + USB power cable + data plan)
They use a  [Spot satellite tracker](http://www.findmespot.eu/shop/index.php?main_page=product_info&cPath=5&products_id=32) which costs around 102€ (125€ with VAT)

plus a [data service plan](http://www.findmespot.eu/en/index.php?cid=131) which costs 10€ a month.

**3. 434,485MHz beacon**
As for the 434,485MHz beacon, it can actually be added as an extra option to the APRS transmitter, both to the [Habduino kit](https://store.uputronics.com/index.php?route=product/product&path=62&product_id=57) and to the [Pi in the Sky kit](https://store.uputronics.com/index.php?route=product/product&path=62&product_id=52)

Finally a list of different tracking options can be found [here](https://community.balloonchallenge.org/t/current-gps-tracker-products/668)
