### ISSUE TITLE
Migrar github para gitlab

### ISSUE THREAD

**Issue by O2F** [vascobnunes/CSWspacepeek#24]
http://doc.gitlab.com/ee/workflow/importing/import_projects_from_github.html
- Vai ser necessário a tua participação devido a credenciais no ato da migração
- Se já tivermos o projecto em gitlab, possivelmente será mais facil recrear o mesmo dado que em leitura diagonal vi que o import e feito no ato da criação do projeto no gitlab.

**Comment by framioco** [comment]
Qual é o endereço do gitlab da CSW?

**Comment by vascobnunes** [comment]
https://gitlab.critical.pt

O gitlab é p a critical toda, mas depois há equipas às quais se podem associar projectos. Há já uma equipa do fikalab por isso faz sentido criar o projecto dentro da equipa.
