### ISSUE TITLE
Criar listagem de hardware necessário

### ISSUE THREAD

**Issue by vascobnunes** [vascobnunes/CSWspacepeek#3]

**Comment by vascobnunes** [comment]
O @rafaelluissantos vai enviar uma lista para a comissão do FikaLab. A lista está aqui:
https://dl.dropboxusercontent.com/u/18901524/CSW%E2%80%99s%20space%20peek%20-%20hardware.png

**Comment by rsnullptr** [comment]
E-mail sent. Vamos aguardar que o André do Fika diga algo.

**Comment by vascobnunes** [comment]
resposta do andré - fikalab:

"Acho que têm aí uma ideia muito interessante. É mesmo esse o tipo de ideias que aqui o pessoal do FikaLab queria ver. :-D

Aqui vão algumas alternativas de material semelhante que temos já aqui disponível no FikaLab, e que podem já começar a experimentar, se quiserem:

Alternativa 1:
https://drive.google.com/open?id=0B69oP6B9IdlkRHdSOUhXOTdiUEE
- LinkIt One: http://www.seeedstudio.com/depot/LinkIt-ONE-p-2017.html
  - inclui GPS, GPRS, e SD card
- LinkSprite Camera: https://www.sparkfun.com/products/11610
  - resolução máxima 640x480 :-(

Com esta alternativa, dava para controlar o disparo das fotografias, por 
exemplo uma por segundo, para ser ao mesmo tempo que os dados da posição 
GPS, e dava para gravar tudo sincronizado no cartão SD.

Alternativa 2:
https://drive.google.com/open?id=0B69oP6B9IdlkNGxuQzVBQU9OUG8
- Arch GPRS V2: http://www.seeedstudio.com/depot/Arch-GPRS-V2-p-2026.html
  - inclui GPRS e SD card
- GPS: http://www.seeedstudio.com/depot/Grove-GPS-p-959.html
- LinkSprite Camera: https://www.sparkfun.com/products/11610
  - resolução máxima 640x480 :-(

Esta alternativa é muito semelhante à anterior, é mais uma questão de 
preferência pessoal em relação ao processador.

E temos também aqui um painel solar, que vos poderá ser útil:
https://drive.google.com/open?id=0B69oP6B9IdlkN0VwWjRKdmZDNFE

Mas o custo da vossa lista de material, exactamente como está, parece-me 
bastante razoável, e acho que não haverá problema em adquirí-la 
integralmente, se preferírem."

**Comment by vascobnunes** [comment]
Diria que neste momento temos a seguinte listagem (@rafaelluissantos - dás tu continuidade a isto com o pessoal do Fikalab?):

Fase 1 - Payload
- (OK) Linkit One com GPS, GPRS e SD card - http://www.seeedstudio.com/depot/LinkIt-ONE-p-2017.html
- (OK) Painel solar - https://drive.google.com/open?id=0B69oP6B9IdlkN0VwWjRKdmZDNFE
- (ORDER) Camera compatível com LinkitOne com resolução HD e melhor que 30fps;
- (ORDER) Battery e battery case;
- (ORDER) Temperature sensor compatível com o LinkIT One;
- (ORDER) Humidity sensor compatível com o LinkIT One;
- (ORDER) Accelerometer compatível com o LinkIT One;
- (ORDER) Gyroscope compatível com o LinkIT One;
- (ORDER) Breadboard compatível com o LinkIT One;
- (GET) Caixa para tudo isto;
- (GET) Material isolador;

**Comment by rsnullptr** [comment]
Vamos ver o que diz o André. Alguma coisa posto aqui.

**Comment by rsnullptr** [comment]
UPDATE:

"
Boa tarde André, 

Segue então a listagem do material requisitio e levantado para a CSW Lx:
- 1x LinkitOne;
- 1x Grove IMU;
- 1x Grove Temperature & Humidity.

Vamos iniciar os testes.
Obrigado.
Rafael Santos
"

Let's partyyy

**Comment by rsnullptr** [comment]
MISSING, to acquire after first tests:

Fase 1 - Payload

*_(TO BE CHECKED BY FIKA) *_Painel solar - https://drive.google.com/open?id=0B69oP6B9IdlkN0VwWjRKdmZDNFE

*_(WE MUST FIND ONE SUITABLE) *_Camera compatível com LinkitOne com resolução HD e melhor que 30fps;

*_(ORDER) *_Battery e battery case;

*_(IS THIS NECESSARY?) *_Breadboard compatível com o LinkIT One;

*_(GET, WHICH ONE?) *_Caixa para tudo isto;

*_(GET, WHICH ONE? AND HOW TO USE?) *_Material isolador;

**Comment by vascobnunes** [comment]
A caixa é arranjar esferovite e duct tape e fazer uma. Isto é fácil. 
Material isolador, temos de mandar vir. Está na lista original http://cdn.instructables.com/F1R/BF7O/HQVQ00C9/F1RBF7OHQVQ00C9.LARGE.jpg

**Comment by rsnullptr** [comment]
Ya, mas se queremos que o FIka adquira temos que enviar links e orçamento mais pomposo feito. Depois vemos isso, temos é que começar a mexer com isto.

**Comment by vascobnunes** [comment]
UPDATE:
Fase 1 - Payload

```
(OK) Linkit One com GPS, GPRS e SD card - http://www.seeedstudio.com/depot/LinkIt-ONE-p-2017.html
(OK) Painel solar - https://drive.google.com/open?id=0B69oP6B9IdlkN0VwWjRKdmZDNFE
(ORDER) Camera compatível com LinkitOne com resolução HD e melhor que 30fps;
(ORDER) Battery e battery case;
(OK) Temperature sensor compatível com o LinkIT One;
(OK) Humidity sensor compatível com o LinkIT One;
(OK) Accelerometer compatível com o LinkIT One;
(OK) Gyroscope compatível com o LinkIT One;
(ORDER) Breadboard compatível com o LinkIT One;
(GET) Caixa para tudo isto;
(GET) Material isolador;
```
